### ISSUE TITLE
Domain error in loguniform

### ISSUE THREAD

**Issue by NaSed** [ARM-software/mango#10]
Hi, 
seems that there is a problem with `loguniform` when one of its argument is negative. For example, my code is runnable when the first argument of `loguniform` is positive and it generates domain error when the first argument is a negative number. Any thought on this?

**Comment by sandeep-iitr** [comment]
Thanks for pointing out the issue. 
Mohit, have fixed the issue with the new changes.
You can update your mango installation by pulling in the latest code and doing the install step again. Please let us know if you face any other problems.
