### ISSUE TITLE
Initial points with values and resuming optimizer

### ISSUE THREAD

**Issue by dom-sta** [ARM-software/mango#105]
Thanks for making this great piece of software. It's been working flawlessly in my tests.

Now that it's possible to specify custom initial points (https://github.com/ARM-software/mango/pull/47), I have two questions that are somewhat related to this.

1. Is it also possible to provide function values for the custom initial points? In many cases, for whatever reason, some function values might be known before running the optimization loop. It would be nice if this information could be used, as a single function call could take hours to complete.
2. Is there any way to save the state of an optimization to disk (after it's finished or possibly even periodically during the run) and resume at a later time? Right now, as far as I can tell, `runBayesianOptimizer` always starts from scratch, ignoring whatever is in `tuner.results`.

**Comment by tihom** [comment]
@dom-sta thanks for raising this, we have created a pull request  to add this feature.

**Comment by dom-sta** [comment]
I just noticed a small bug. When running `tuner.minimize()` the initial custom values are multiplied by -1 in the `runBayesianOptimizer()` method. A simple workaround is to multiply the initial custom values by -1 before passing them to the tuner but this is not intuitive and should probably be fixed.

**Comment by tihom** [comment]
@dom-sta 

> I just noticed a small bug. When running `tuner.minimize()` the initial custom values are multiplied by -1 in the `runBayesianOptimizer()` method. A simple workaround is to multiply the initial custom values by -1 before passing them to the tuner but this is not intuitive and should probably be fixed.

@dom-sta thanks for pointing this out. i have fixed this bug in the latest version
