### ISSUE TITLE
Wrong minimum calculation

### ISSUE THREAD

**Issue by schliffen** [ARM-software/mango#111]
I tried the following objective function:
`
def objective(x):
    return (x-1) * (x-2) +1
`
and it returned the wrong answer x=1 and objective value = 1.

code:
`
from mango import scheduler, Tuner
# Search space
param_space = dict(x=range(-10,10))

# Quadratic objective Function
@scheduler.serial
def objective(x):
    return (x-1) * (x-2) +1

# Initialize and run Tuner
tuner = Tuner(param_space, objective)
results = tuner.minimize()

print(f'Optimal value of parameters: {results["best_params"]} and objective: {results["best_objective"]}' )
# => Optimal value of parameters: {'x': 1.5}  and objective: 0.72
`

**Comment by schliffen** [comment]
It seems that only takes integers and the answer is also is integer.

**Comment by sandeep-iitr** [comment]
You can pass in float/non-integer values using proper parameter space definition. 
Your current definition only defines integer `(param_space = dict(x=range(-10,10)))`

Take a look at other parameter spaces shown in the readme like: 

```
from scipy.stats import uniform

# uniformly distributed between -10 and 10
param_space = dict(a=uniform(-10, 20))
```
