### ISSUE TITLE
What to return in case of failure?

### ISSUE THREAD

**Issue by mikephn** [ARM-software/mango#15]
My model returns a NaN loss when a configuration cannot be evaluated. This seems to sometimes be allowed, and sometimes cause a crash. What should be the return value in case of a failure?

> return None

`TypeError: unsupported operand type(s) for *: 'int' and 'NoneType'`

>return float("NaN")

`ValueError: Input contains NaN, infinity or a value too large for dtype('float64').`

Many thanks.

**Comment by sandeep-iitr** [comment]
Thanks for asking the question. One way to handle it using the below syntax. 
The objective function return can be a list of successful parameters evaluated via a list of
evaluations and respective hyperparameters. In case none is successful, the empty list can be returned.

A simple example is here: https://github.com/ARM-software/mango/blob/master/examples/Failure_Handling.ipynb

**Comment by mikephn** [comment]
Thank you, it works when returning two empty lists. The issue seems to be using the @scheduler.serial decorator. This works:

```python
def objective(params):
    if np.random.randint(0, 3) == 0:
        print('failure')
        return [], []
    print('valid')
    return params, [5]
```
but this doesn't:

```python
@scheduler.serial
def objective(**params):
    if np.random.randint(0, 3) == 0:
        print('failure')
        return [], []
    print('valid')
    return [params], [5]
```

`TypeError: unsupported operand type(s) for *: 'int' and 'dict'`

**Comment by sandeep-iitr** [comment]
@scheduler decorator functions expect a return value, as you mentioned as well.

A better approach for deployment settings where there are failures are is to use the general objective function syntax, which I mentioned to you in my earlier reply. This objective function syntax is kept outside Mango, to allow flexibility in scheduling the way it is needed. 
In this scheduler, the user can return earlier before evaluating all the hyperparameters in the list. Also, the objective function can keep track of failed values, and avoid similar/nearby hyperparameters for scheduling in the future.

@scheduler decorators are an easy way to parallelize on the local machine for users using @scheduler.parallel
We will augment these scheduler definitions as well soon to allow empty results.

**Comment by sandeep-iitr** [comment]
Also, as you mentioned, @Scheduler decorator expects a singular return value. The list values are supported for general objective function syntax. We will allow empty values in the scheduler with changes done soon.

**Comment by mikephn** [comment]
Hello, has this issue been solved now for @parallel scheduler? I would like to use it and be able to handle failed evaluations, but nothing I tried works (returning None or empty list).

Many thanks.

**Comment by tihom** [comment]
@mikephn the @parallel and @serial scheduler cannot handle failures as the user needs to specify which exceptions to catch.

We have written an [example](https://github.com/ARM-software/mango/blob/master/examples/Failure_Handling_Parallel.ipynb) that shows how to run a parallel search while handling failures. Hopefully that will help you write your own version.
