### ISSUE TITLE
clustering mode scikit-learn>=0.23.0 bug

### ISSUE THREAD

**Issue by flamby** [ARM-software/mango#18]
Hello,

Clustering mode seems to require scikit-learn<0.23.0, at least with my search space.
Otherwise, I get the following error after the first iteration:

```python
/.virtualenvs/lib/python3.8/site-packages/mango/tuner.py in maximize(self)
    126
    127     def maximize(self):
--> 128         return self.run()
    129
    130     def minimize(self):

~/.virtualenvs/lib/python3.8/site-packages/mango/tuner.py in run(self)
    117     def run(self):
    118         if self.config.is_bayesian:
--> 119             self.results = self.runBayesianOptimizer()
    120         elif self.config.is_random:
    121             self.results = self.runRandomOptimizer()

~/.virtualenvs/lib/python3.8/site-packages/mango/tuner.py in runBayesianOptimizer(self)
    194                                                     batch_size=self.config.batch_size)
    195             elif self.config.strategy_is_clustering:
--> 196                 X_next_batch = Optimizer.get_next_batch_clustering(X_sample,Y_scaled, X_domain_np,
    197                                                                    batch_size=self.config.batch_size)
    198             else:

~/.virtualenvs/lib/python3.8/site-packages/mango/optimizer/bayesian_learning.py in get_next_batch_clustering(self, X, Y, X_tries, batch_size)
    290
    291             # Do the domain space based clustering on the best points
--> 292             kmeans = KMeans(n_clusters=batch_size, random_state=0).fit(x_best_acq_domain)
    293             cluster_pred_domain = kmeans.labels_.reshape(kmeans.labels_.shape[0])
    294

~/.virtualenvs/lib/python3.8/site-packages/sklearn/cluster/_kmeans.py in fit(self, X, y, sample_weight)
    995         # verify that the number of samples given is larger than k
    996         if _num_samples(X) < self.n_clusters:
--> 997             raise ValueError("n_samples=%d should be >= n_clusters=%d" % (
    998                 _num_samples(X), self.n_clusters))
    999

ValueError: n_samples=2 should be >= n_clusters=4
```
**My conf_dict**
```
conf_dict = {
    "batch_size": 4,
    "num_iteration": 100,
    "parallel_strategy": "clustering",
}
```

Looking at the scikit-learn changelog, we see lots of KMeans changes during 0.23 cycle:
https://scikit-learn.org/stable/whats_new/v0.23.html#version-0-23-2

I was able to pin point the exact version which introduced the issue: **0.23.0**
I think a simple `'scikit_learn>=0.21.3, <0.23.0'` in `setup.py` will do the trick, until you find how to fix it for these `KMeans` changes.

So the latest `scikit-learn` version suitable for clustering mode is 0.22.2.post1, which luckily I had on the server I used initially.

BTW the clustering mode does converge faster indeed. Thank you very much!

**Comment by sandeep-iitr** [comment]
Thank you for letting us know, and for your investigation. We will look into it and followup soon. 
We are aware of this issue and have fixed it in another branch. We will try to integrate the changes to the master branch.

regards.

**Comment by flamby** [comment]
thanks @sandeep-iitr 

I take this opportunity to ask if you've considered (and if it makes sense) replacing KMeans by Hierarchical Clustering?
Since KMeans tends to generate nearly identical cluster sizes (due to the uniform effect), and Hierarchical Clustering can use many form of distance metrics (non euclidean metric; like jaccard similarity useful for binary categorical variables).

Also, it seems mango rely on a bayesian UCB algorithm for multi-arm bandit. Have you considered using Thompson Sampling? 
Just a reflection following [this interesting article ](https://lilianweng.github.io/lil-log/2018/01/23/the-multi-armed-bandit-problem-and-its-solutions.html)

**Comment by sandeep-iitr** [comment]
Thanks for your suggestions. We will be happy to investigate the usage of Hierarchical Clustering.

The core idea behind the clustering algorithm is to create different spatial regions in the search space so as to explore them parallelly. The main challenge in this is to ensure that the selected batch is doing exploration in different regions from the high reward peaks. A naive parallel approach often lacks proper exploration.

With this goal, any clustering algorithm will be fine as long as clusters are spatially distinct. Before clustering, we ensure that high rewarding regions are only clustered. However, as you suggest better clustering may be able to help or speed up this approach.

Mango does rely on the bayesian UCB algorithm. One way to sample values is to use Thompson Sampling, which is also used by developers. We have paid particular attention to enable efficient parallel search, so we use penalty and clustering over the acquisition function (UCB) to ensure the implemented parallel algorithms are superior with some theoretical guarantees. Thompson sampling can also be used to do a parallel search, however, it doesn't ensure different samples in the same batch will do proper exploration as needed, to the best of my knowledge.

We are working on doing extensive benchmarking of Mango by comparing it to other frameworks and libraries. Results are showing Mango's algorithms perform better in comparison to naive parallelism or sequential methods. We will make this report available as a paper soon in the next ~20 days.
Again thanks for the suggestions.

**Comment by flamby** [comment]
thanks for the clarification @sandeep-iitr 

Since yesterday, I'm raising an issue with `clustering` strategy (`penalty` is fine w/ the very same search space) that I can reproduce at will. Have you encounter that?

```python
-> 2346     results = tuner.maximize()
   2347     print('best parameters:', results['best_params'])
   2348     print('best accuracy:', results['best_objective'])

~/.virtualenvs/lib/python3.8/site-packages/mango/tuner.py in maximize(self)
    126
    127     def maximize(self):
--> 128         return self.run()
    129
    130     def minimize(self):

~/.virtualenvs/lib/python3.8/site-packages/mango/tuner.py in run(self)
    117     def run(self):
    118         if self.config.is_bayesian:
--> 119             self.results = self.runBayesianOptimizer()
    120         elif self.config.is_random:
    121             self.results = self.runRandomOptimizer()

~/.virtualenvs/lib/python3.8/site-packages/mango/tuner.py in runBayesianOptimizer(self)
    194                                                     batch_size=self.config.batch_size)
    195             elif self.config.strategy_is_clustering:
--> 196                 X_next_batch = Optimizer.get_next_batch_clustering(X_sample,Y_scaled, X_domain_np,
    197                                                                    batch_size=self.config.batch_size)
    198             else:

~/.virtualenvs/lib/python3.8/site-packages/mango/optimizer/bayesian_learning.py in get_next_batch_clustering(self, X, Y, X_tries, batch_size)
    290
    291             # Do the domain space based clustering on the best points
--> 292             kmeans = KMeans(n_clusters=batch_size, random_state=0).fit(x_best_acq_domain)
    293             cluster_pred_domain = kmeans.labels_.reshape(kmeans.labels_.shape[0])
    294

~/.virtualenvs/lib/python3.8/site-packages/sklearn/cluster/_kmeans.py in fit(self, X, y, sample_weight)
    860         # verify that the number of samples given is larger than k
    861         if _num_samples(X) < self.n_clusters:
--> 862             raise ValueError("n_samples=%d should be >= n_clusters=%d" % (
    863                 _num_samples(X), self.n_clusters))
    864

ValueError: n_samples=1 should be >= n_clusters=4
```
Switching to `penalty` strategy works, despite converging slower and in the end having worst results, based on a dozen of trials of clustering vs penalty with my dataset and search spaces.

The issue seems to be related to the search space size, as if I reduce it, I'm able to have a successful `clustering` run.

For now, as a workaround, I'm doing smaller searches, iteratively, but maybe there is a better way to tackle this.

Thanks!

**Comment by sandeep-iitr** [comment]
Sorry for the delayed response. We were busy due to a deadline. 
The fix for this problem is simple and is available with us. We will integrate the fix to the master branch by next week.
