### ISSUE TITLE
early stopping ?

### ISSUE THREAD

**Issue by asah** [ARM-software/mango#19]
Have you considered support for stopping Mango early if the objective function doesn't improve enough?

Would you be open to a contribution PR?

thanks!

**Comment by sandeep-iitr** [comment]
Thanks. We will be happy to have suggestions and possible contributions. We are a little busy for the next ~4 days due to a deadline. The early stopping strategies are definitely one of our future planned works, and we plan to integrate it into Mango.

**Comment by flamby** [comment]
+1

I've done something in the same vein that might be useful like early stopping: displaying current best params every time the progress bar changes. I'm launching the search with a huge `num_iteration` and stop it when I see a satisfying result

**tuner.py**
_For Bayesian optimizer_
```python
237             pbar.set_description("Best score: %s" % np.max(Y_sample))
238             print(hyper_parameters_tried[np.argmax(Y_sample)])
```
_For random_
```python
274             pbar.set_description("Best score: %s" % np.max(np.array(Y_sample_list)))
275             print(X_sample_list[np.argmax(Y_sample_list)])
```

**Comment by asah** [comment]
PR submitted - request changes and I'll gladly make them!
https://github.com/ARM-software/mango/pull/21

**Comment by sandeep-iitr** [comment]
Thanks for the PR. Please give us some time to review.

**Comment by asah** [comment]
Ping? Thx.

**Comment by tihom** [comment]
@asah Thanks for the PR. Inspired by your suggestion, we are currently developing a feature that would allow early_stopping using custom callback provided by the user. This would allow uses to specify custom criteria for early_stopping like a threshold for the objective functions, elapsed iterations since last improvement etc. We would submit a PR this week and welcome your feedback on it.

**Comment by asah** [comment]
perfect!  custom callback makes the most sense, especially if a few
examples are included.

**Comment by tihom** [comment]
@asah see the PR #24 and the [https://github.com/ARM-software/mango/blob/aa7ee8241dc6e9fe8168f092073d8aabeab3aa6d/tests/test_tuner.py#L351](test) that demos your use case for min improvement secs. Let us know if that resolves your request. We would add some examples in docs once the PR is finalized.

**Comment by asah** [comment]
this is awesome, yes it does!
