### ISSUE TITLE
Bayesian Learning constant increase time between iterations, search space & memory constraint

### ISSUE THREAD

**Issue by flamby** [ARM-software/mango#22]
Hello,

First of all, thanks for the `KMeans` fix in the master branch, it fixed the `scikit-learn>=0.23` issue.

Right now, I can't really use the `Bayesian` optimizer since most of the time spent for every iterations is not spent in the objective function (in my case celery tasks) but in the analysis of their results, a time that is increasing linearly after every iteration.

To decide between `Bayesian` or `Random` optimization, if one count only the number of iterations, then the `Bayesian` optimizer is a clear winner because of its fast convergence, but from a duration perspective, `Random` optimizer is an order of magnitude better, at least with my dataset / search space. When the batch of celery tasks is finished, I see only one processor used at 100% (so the bottleneck is a mono-threaded process) during several minutes, and this time (idle time from a celery perspective) is increasing linearly, iteration after iteration.
For instance:
- iteration 1: 124s/it
- iteration 2: 168s/it
- iteration 3: 239s/it
- iteration 4: 329s/it
- etc.

The very same search space using the `Random` optimizer displays a constant duration :
- iteration 1: between 100 and 140s/it (which is approximately the time the celery task batch takes with full usage of the celery workers)
- [...]
- iteration 100: between 100 and 140s/it

Also, `Bayesian` optimizer seems to not handle lots of parameters in the search space, whereas random (which is quite obvious) can by a lot. If I try to do a bayesian search on a large search space, I get an out of memory error very quickly (even on a 256GB RAM server where the mango process is launched ; i.e. it's not a celery memory constraint at all).

So, with my very limited python optimization knowledge, I tried to improve the bayesian module by doing some metering, discovering that the Kmeans algorithm was not responsible for this linear analysis time increase, but most probably the GaussianProcessRegressor / multi-arm bandit functions themselves were.

I tried adding the [numba @njit or @jit decorators](https://numba.pydata.org/numba-doc/latest/user/5minguide.html#what-is-nopython-mode) which brings easily _just in time_ compilation optimization, but most methods of the `BayesianLearning` class don't support it without modifications, and the ones that accept it did not lead to a significant improvement.

Are you aware of such limitations? Is there some room for improvement regarding monothreaded processing time and large search space support without memory constraint?

Relying right now on the `Random` optimizer brings me to a last question: how better it is compared to a RandomGridSearch from `scikit-learn` for instance? Looking at the code, it seems there is no clustering involved, right?  So no real intelligence so to speak in the tested parameters, iteration after iteration.

Thanks!

**Comment by sandeep-iitr** [comment]
Thanks for the issue. 

Your problem looks interesting. 

While it is true that Bayesian will be slower and its runtime will increase slightly with each iteration. In the current master branch, we have made it faster by using Monte-Carlo sampling for optimization instead of the Gradient-based approach, which is traditionally used in typical systems. 

We have made changes to our branch to decrease its running time of the optimizer further using techniques to do avoid unnecessary sampling between iterations. We will push them to the master branch and will allow users to enable them. We will try to do it soon, and then let you know

Looking at the fact that you get out of memory error on the 256GB RAM server, it seems something is not happening right.
Practically, the Bayesian process shouldn't take this much memory. Maybe the celery tasks are not cleaning up the memory. 
We have never faced this in our current production deployments.
Can you share more details about the search space definition you are using and the number of tasks you are running in parallel?
If you are not running tasks on a cluster, then celery workers might not help with speedup, and directly using parallel jobs might be a good idea. 
Another thing is knowing your search space design, I can suggest you a quick-trick to make your iterations notably faster by making a one-line code change. There are also other few changes possible in the code for your case, that I can suggest knowing more details to make it further 2-3 times faster (like reducing the number of times the bayesian process is restarted for each iteration).

regards,
Sandeep

**Comment by flamby** [comment]
Hi @sandeep-iitr 

Thanks for your answer.

> We have made changes to our branch to decrease its running time of the optimizer further using techniques to do avoid unnecessary sampling between iterations. We will push them to the master branch and will allow users to enable them. We will try to do it soon, and then let you know

I'll be glad to test it ;-)


> Looking at the fact that you get out of memory error on the 256GB RAM server, it seems something is not happening right.
> Practically, the Bayesian process shouldn't take this much memory. Maybe the celery tasks are not cleaning up the memory.

The server where I'm getting the oom killer is the one where I run mango (256GB of RAM, no celery workers there). The servers where celery worker are (20 server 4CPU/16GB RAM) running the tasks aren't affected at all by that memory issue.

>We have never faced this in our current production deployments.
>Can you share more details about the search space definition you are using and the number of tasks you are running in parallel?

Sure.
I can reproduce at will the issue with a such search space:
```python
param_space = {
    "threshold": range(250, 1025, 25),
    "steps": [50, 100],
    "features": all_features_combinations,
}
```
where `all_features_combinations` is a list of 367290 sub-list (with 4 strings per sub-list)
e.g. something like this
```python
 all_features_combinations = [
    ["A-1", "A-2", "A-3", "A-4"],
    ["A-1", "A-2", "A-3", "A-5"],
    ["A-1", "A-2", "A-3", "A-6"],
    [...]
]
```
`all_features_combinations` is basicaly the result of that:
```python
import itertools
all_functions = ["A"]
features_search_space = {
    "func_name": all_functions,
    "value": range(2, 31),
}
combinaisons_features = [f"{c['func_name']}-{c['value']}" for c in
                                     (dict(zip(features_search_space, x)) \
                                      for x in itertools.product(*features_search_space.values()))]
all_features_combinations = [list(c) for c in itertools.combinations(combinaisons_features, 4)]
```
I think my issue might be due to the very high number of categorical variables, which are then one-hot encoded, leading to memory issue, then slowing exponentially every iteration. If so, it would be very specific to my use-case, which differ probably from the regular usage of mango (hyper-parameter grid-searching).

I also have other search spaces, raising the issue too, consisting of combinations of dict and sub-dict, and I guess they are also somehow one-hot encoded, despite this search space structure is more in-line with hyperparameter search.
A such search space would look like this:
```python
param_space = {
    "threshold": range(250, 1025, 25),
    "steps": [50, 100],
    "other_params": all_other_params,
    "other_features": all_other_features,
}
```
where `other_params` looks like this
```
other_params = [
[{"feature": "A", "time_unit": 1, "func": "MY_FUNC_1", "period": 1}, {"feature": "A", "time_unit": 2, "func": "MY_FUNC_1", "period": 1}, {"feature": "A", "time_unit": 3, "func": "MY_FUNC_1", "period": 1}],
[{"feature": "B", "time_unit": 1, "func": "MY_FUNC_1", "period": 1}, {"feature": "B", "time_unit": 2, "func": "MY_FUNC_1", "period": 1}, {"feature": "B", "time_unit": 3, "func": "MY_FUNC_1", "period": 1}],
[...]
]
```
and `all_other_params` looks like this
```
other_features = [
[{"feature": "A", "lag": 1}, {"feature": "A", "lag": 2}],
[{"feature": "A", "lag": 1}, {"feature": "A", "lag": 3}],
[...]
]
```
> We have never faced this in our current production deployments.
> Can you share more details about the search space definition you are using and the number of tasks you are running in parallel?

See above information.

> If you are not running tasks on a cluster, then celery workers might not help with speedup, and directly using parallel jobs might be a good idea.

I'm not sure I get what you mean here. Every task is very cpu/ram intensive and is taking all resources of the server where it is running (one task in // per server ; 20 servers in total ; 4 CPU and 8GB of RAM per server, an average of 120seconds per task completion). It's impossible to launch all tasks in // on the very same server for i/o and cpu/ram ressources reasons.

> Another thing is knowing your search space design, I can suggest you a quick-trick to make your iterations notably faster by making a one-line code change. There are also other few changes possible in the code for your case, that I can suggest knowing more details to make it further 2-3 times faster (like reducing the number of times the bayesian process is restarted for each iteration).

Maybe you mean reducing `n_restarts_optimizer` of the `GaussianProcessRegressor`. If so, I already tried to reduce it to 2 and 1, without much improvement.

Thanks!

**Comment by flamby** [comment]
Hello,

I've tested release 1.1, and it seems to fix my issues.
By reducing domain_size (from default 50000 minimum?) to 5000 or less, I no longer get rapidly huge memory usage.
Also, iterations' duration mostly stay the same, or increase less than before.

Kudos!

**Comment by sandeep-iitr** [comment]
I see. Good to know.
Yes, reducing domain size in your case will help a lot to speed things up.
You can control domain size as below:

```
conf_Dict = dict()
conf_Dict['domain_size'] = 5000
conf_Dict['num_iteration'] = ...
...

tuner_user = Tuner(param_dict, objective, conf_Dict)

```
