### ISSUE TITLE
ValueError: XA and XB must have the same number of columns (i.e. feature dimension.)

### ISSUE THREAD

**Issue by markustoivonen** [ARM-software/mango#32]
Hi!

I am running Mango 1.1.0 for a HPS. After a few iterations in, I get the following error logs:

![image](https://user-images.githubusercontent.com/24810115/119533743-d9157580-bd8e-11eb-9138-5362114fd087.png)

My params to search area:

```
param_dict = {"param1": uniform(0.01, 1),
              "param2": uniform(0.01, 1),
             "param3": uniform(0.01, 1),
             "param4": uniform(0, 1),
             "param5": uniform(0.5, 0.49)}
```

I am running the default configuration parameters.

Any ideas what might cause this or how to fix?

**Comment by tihom** [comment]
@markustoivonen please send the more details so that we can reproduce the bug.

**Comment by sandeep-iitr** [comment]
Closing in failure to reproduce.
