### ISSUE TITLE
Question about the definition of num_iteration

### ISSUE THREAD

**Issue by zoechoutw** [ARM-software/mango#96]
Hi,

I set the num_iteration=25 and initial_random=10, and n_jobs=4. However, the time cost is longer using @scheduler.parallel than using @scheduler.serial. I wonder why using parallel Bayesian optimization is slower? I supposed that the numbers of the total samples they generate are same which is (25+10=35) ? Please correct me if I misunderstand. Thank you!

**Comment by sandeep-iitr** [comment]
When you set the n_jobs=4, the total samples generated are 25*4 + 10 = 110. So it is slower due to that. Internally, Mango runs 4 jobs parallelly per iteration each running using a sample. So, in this case, you can set a lower iteration when running in parallel for the same number of samples.
